name: CI
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained false
          dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained false
          dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained false
          dotnet publish -r osx.13-arm64 -p:PublishSingleFile=true --self-contained false
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          retention-days: 30
          path: "bin/Debug/win-x64/publish/*"
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          retention-days: 30
          path: "bin/Debug/linux-x64/publish/*"
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS
          retention-days: 30
          path: "bin/Debug/osx.13-arm64/publish/*"
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOSx64
          retention-days: 30
          path: "bin/Debug/osx-x64/publish/*"